export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const GUIDE_ROUTE = '/guide'
export const PRACTICE_ROUTE = '/practice'
export const HOME_ROUTE = '/home'
export const TEST_ROUTE = '/test'